[env:esp32doit-devkit-v1]
platform = espressif32@6.12.0
board = esp32doit-devkit-v1
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
build_flags = 
    -Wl,-zmuldefs
    -D CONFIG_SPIRAM_SPEED_80M
    -D CONFIG_SPIRAM
monitor_filters = 
    esp32_exception_decoder
    direct
board_build.psram = enabled